name: Build and deploy Python project to Azure Function App - af-function-tester

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './extracted' # Deploy from extracted folder
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt -t .  # Ensures dependencies are included

      - name: Zip artifact for deployment
        run: zip -r release.zip * -x "venv/*" ".git/*" ".github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C0F156B25E14AB38A4882EFE7258287 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE2B1041738E4BA19A0C4D9BE34FACB9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E8FBE910EC74B98ADC68B2ED18CD0B0 }}

      - name: Unzip artifact for deployment
        run: unzip release.zip -d extracted  # Extract into a new folder

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'af-function-tester'
          package: './extracted'  # Deploy from extracted folder